### ISSUE TITLE
Bug? Missing keys after backup then restore of a large db

### ISSUE THREAD

**Issue by osiloke** [dgraph-io/badger#401]
I'm having trouble grasping the results of backing up and restoring a badgered database.
I have a database which has a couple thousand entries. I run badger_info which gives me the result below:
```
> badger_info --dir original_db
[Manifest]
MANIFEST           1562  2018-01-18T10:37:32+01:00
[Level 0]
000085.sst        15587  2018-01-18T10:22:43+01:00 0
[Level 1]
000084.sst       362235  2018-01-15T19:39:06+01:00 1
[Value Log]
000000.vlog     4286777  2018-01-18T10:37:32+01:00
[Summary]
Level 0 size: 15587
Level 1 size: 362235
Total index size: 377822
Value log size: 4286777
Abnormalities: None.
0 extra files.
0 missing files.
0 empty files.
0 truncated manifests.
```
I run badger backup to backup the the database. Then i restore the database to a different folder and run badger_info which then gives me the result below.

```
> badger_info --dir new_db
[Manifest]
MANIFEST             28  2018-01-18T11:03:15+01:00
[Level 0]
000001.sst       111648  2018-01-18T11:03:15+01:00 0
[Value Log]
000000.vlog     3414691  2018-01-18T11:03:15+01:00
[Summary]
Level 0 size: 111648
Total index size: 111648
Value log size: 3414691
Abnormalities: None.
0 extra files.
0 missing files.
0 empty files.
0 truncated manifests.
```
I assume it compacted the database to just level 0 based on this result. if i tail the value log i can see that it has at least most of the entries.

This all looks fine, based on my assumptions, until i iterate all keys using the snippet from the docs. It returns only 3 keys.
This does not seem to correlate with the metric data returned by badger_info

**Comment by Draal** [comment]
I hit the same issue with backup / restore, this is the gist which reproduces it
https://gist.github.com/Draal/f7feb3f5ca58d5902ff134e446de31b1

I've tried different options/closing opening, etc with no luck.

**Comment by MoZhonghua** [comment]
I found the db.orc.curRead is not updated after item loaded,  so later txn can only see item with ts == 0. Two ways to fix:
  1. set db.orc.curRead to max(db.orc.curRead, max(ts of entries)) after load
  2. ignore item's old timestamp and re-insert them using normal txn

**Comment by janardhan1993** [comment]
Fixed in master.

**Comment by Draal** [comment]
@janardhan1993  unfortunately the fix in master didn't fix the case below:
1) First insert some rows into DB1
2) Backup it
3) Restore the result snapshot into DB2
4) Set the same keys
5) Backup DB2
6) Restore DB2 into DB3
7) Keys are not there
The gist which replicates this:
https://gist.github.com/Draal/aeec21ee8260e33e2bf4de2bd4ecb4d4

```go test
backup1 length: 24320
backup2 length: 48800
--- FAIL: Test_BackupRestore (0.10s)
	badger_snapshot_test.go:135: Key [116 101 115 116 115 110 97 112 115 104 111 116 58 107 101 121 49 0] has been not found, but was set

FAIL```
