### ISSUE TITLE
partial vlog will cause badger panic

### ISSUE THREAD

**Issue by MoZhonghua** [dgraph-io/badger#408]
Suppose following steps:

1. open db, open txn, write (1-1000) items, commit; vlog just write 500 items and crash

2. re-open db, these 500 items will not be write to LSM becasuse there is no TxnFin for them

3. open txn, write (1001, 2000) items, commit; vlog write data and crash before these data written to LSM (this brute sequence shoud make badger to replay vlog when open)

4. Now, there are following items in vlog:
    <item1 ... item500> with ts = 1
    // no [TxnFin for ts=1]
   <item1001 ...item2000>
   [TxnFin for ts=2]

5. When replay, badger panic because it get ts=2 without TxnFin for ts=1. 
   IMHO, it should just discard all items with ts=1 and write items with ts=2 to LSM .

**Comment by janardhan1993** [comment]
@MoZhonghua Can you please try to reproduce this using jan/partial_vlog branch

**Comment by janardhan1993** [comment]
I have submitted a fix in #412

**Comment by MoZhonghua** [comment]
There is one more location to fix: replayFunction() in db.go. 

I create parital vlog using following steps:

- abort vlog.write() forcely when one block is written

```diff
diff --git a/value.go b/value.go
index 18e74f2..94434d0 100644
--- a/value.go
+++ b/value.go
@@ -795,12 +795,13 @@ func (vlog *valueLog) write(reqs []*request) error {
                        b.Ptrs = append(b.Ptrs, p)
 
                        if p.Offset > uint32(vlog.opt.ValueLogFileSize) {
                                if err := toDisk(); err != nil {
                                        return err
                                }
+                               os.Exit(0)
                        }
                }
        }
        return toDisk()
 
        // Acquire mutex locks around this manipulation, so that the reads don't try to use

```

- create txn that will generate write larger than ValueLogFileSize
```go
package main

import (
	"fmt"
	"log"
	"math/rand"

	"github.com/dgraph-io/badger"
)

func main() {
	log.SetFlags(log.LstdFlags | log.Lshortfile)
	opts := badger.DefaultOptions
	opts.Dir = "./badgerdb"
	opts.ValueDir = "./badgerdb"
	opts.ValueLogFileSize = 1024 * 1024

	db, err := badger.Open(opts)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	updates := make(map[string][]byte)
	val := make([]byte, 2048)
	rand.Read(val)
	for i := 0; i < 1024; i += 1 {
		k := fmt.Sprintf("%03d", i)
		updates[k] = val
	}

	txn := db.NewTransaction(true)
	for k, v := range updates {
		err = txn.Set([]byte(k), v)
	}
	_ = txn.Commit(nil)
}

```

- run the test script three times, and got following panic
```bash
2018/01/31 14:00:52 error.go:55: Assert failed
github.com/dgraph-io/badger/y.AssertTrue
	/home/mzh/go/src/github.com/dgraph-io/badger/y/error.go:55
github.com/dgraph-io/badger.replayFunction.func2
	/home/mzh/go/src/github.com/dgraph-io/badger/db.go:157
github.com/dgraph-io/badger.(*valueLog).iterate
	/home/mzh/go/src/github.com/dgraph-io/badger/value.go:299
github.com/dgraph-io/badger.(*valueLog).Replay
	/home/mzh/go/src/github.com/dgraph-io/badger/value.go:676
github.com/dgraph-io/badger.Open
	/home/mzh/go/src/github.com/dgraph-io/badger/db.go:291
main.main
	/home/mzh/go/src/playground/badger_partial_vlog/main.go:18
runtime.main
	/usr/lib/go/src/runtime/proc.go:195
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:2337
```

**Comment by janardhan1993** [comment]
Doing a fix in replay function might cause other issues, so having an assert there is good i think. It's best to truncate the file instead of ignoring it during replay as we can have tricky scenarios due to value log GC.

I think by ensuring all entries of a single transaction are always written to the same value log file, we won't face the above issue.

**Comment by manishrjain** [comment]
Is this fixed now, @janardhan1993 ?

**Comment by zboralski** [comment]
I still have this issue

https://github.com/dgraph-io/dgraph/issues/2341
